project:
  type: website

lang: pt-BR

bibliography: bibliografia.bib

website:
  title: Teoria das Categorias no Brasil
  navbar:
    background: primary
    collapse-below: lg
    right:
      - o-que-e.qmd
      - blog.qmd
      - pesquisadores.qmd
      - laboratorios.qmd
      - eventos.qmd
      - acervo.qmd
      - participe.qmd
  page-footer:
    left: "Sugestões ou dúvidas? [categoriasbrasil@gmail.com](mailto:categoriasbrasil@gmail.com)"
    center: "Teoria das Categorias no Brasil"
    right: 
      - text: "Este é um site de código aberto"
      - icon: github
        href: https://github.com/categorias-brasil/categorias-brasil.github.io
format:
  html:
    html-math-method: katex
    theme:
      light: [flatly, custom.scss]
      dark: [darkly, custom-dark.scss]
    monofont: JuliaMono-Regular

from: markdown+tex_math_single_backslash

filters:
  - filters.lua
